# Generated by Django 4.2.5 on 2023-09-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_task_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='days',
            field=models.CharField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=10, null=True),
        ),
    ]
