# Generated by Django 4.2.5 on 2023-09-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_weekdays_remove_task_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='list.weekdays'),
        ),
    ]
