# Generated by Django 4.2.5 on 2023-09-29 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_task_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.weekdays'),
        ),
    ]
