# Generated by Django 4.2.5 on 2023-09-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_alter_task_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='day',
        ),
        migrations.AddField(
            model_name='task',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='WeekDays',
        ),
    ]
