# Generated by Django 4.2.5 on 2023-09-29 18:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0009_remove_task_day_task_days_delete_weekdays'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('user',)},
        ),
    ]
