# Generated by Django 4.2.5 on 2023-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_alter_task_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='days',
            field=models.CharField(choices=[], max_length=20, null=True),
        ),
    ]
