# Generated by Django 4.2.5 on 2023-10-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0016_alter_task_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesdy', 'Wednesday'), ('Thursdy', 'Thursday'), ('Friday', 'Friday'), ('Saturdy', 'Sturday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
    ]
