# Generated by Django 4.2.5 on 2023-10-02 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0021_alter_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='user',
        ),
    ]
